export const LOGIN_REQUEST: 'LOGIN_REQUEST' = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS' = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED' = "LOGIN_REQUEST_FAILED";

export const REGISTER_REQUEST: 'REGISTER_REQUEST' = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS: 'REGISTER_REQUEST_SUCCESS' = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_FAILED: 'REGISTER_REQUEST_FAILED' = "REGISTER_REQUEST_FAILED";

export const PROFILE_REQUEST: 'PROFILE_REQUEST' = "PROFILE_REQUEST";
export const PROFILE_REQUEST_SUCCESS: 'PROFILE_REQUEST_SUCCESS' = "PROFILE_REQUEST_SUCCESS";
export const PROFILE_REQUEST_FAILED: 'PROFILE_REQUEST_FAILED' = "PROFILE_REQUEST_FAILED";

export const PROFILE_UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST' = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS' = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED' = "PROFILE_UPDATE_FAILED";

export const CLEAR_PROFILE_SUCCESS: 'CLEAR_PROFILE_SUCCESS' = "CLEAR_PROFILE_SUCCESS";
export const AUTH_CHECK: 'AUTH_CHECK' = "AUTH_CHECK";

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = "LOGOUT_REQUEST";
export const LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS' = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_FAILED: 'LOGOUT_REQUEST_FAILED' = "LOGOUT_REQUEST_FAILED";
export const LOGOUT_CLEAR_PROFILE: 'LOGOUT_CLEAR_PROFILE' = "LOGOUT_CLEAR_PROFILE";

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = "RESET_PASSWORD_FAILED";

export const SAVE_RESET_PASSWORD_REQUEST: 'SAVE_RESET_PASSWORD_REQUEST' = "SAVE_RESET_PASSWORD_REQUEST";
export const SAVE_RESET_PASSWORD_SUCCESS: 'SAVE_RESET_PASSWORD_SUCCESS' = "SAVE_RESET_PASSWORD_SUCCESS";
export const SAVE_RESET_PASSWORD_FAILED: 'SAVE_RESET_PASSWORD_FAILED' = "SAVE_RESET_PASSWORD_FAILED";
export const CLEAR_RESTORE_FLAGS: 'CLEAR_RESTORE_FLAGS' = "CLEAR_RESTORE_FLAGS";

export const CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE' = "CLEAR_ERROR_MESSAGE";